# Generated by Django 4.1.1 on 2022-12-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_alter_pregunta_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['creado'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
