# Generated by Django 4.1.3 on 2022-12-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_alter_pregunta_options_quiz_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='quizz.quiz'),
        ),
    ]
