# Generated by Django 4.1.3 on 2022-12-10 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0004_alter_pregunta_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponderacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ponderacion',
            name='usuario',
            field=models.ManyToManyField(related_name='user_puntuacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
