# Generated by Django 4.1.3 on 2022-12-10 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0005_remove_ponderacion_usuario_ponderacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponderacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ponderacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_puntuacion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
